import {
  Star,
  Award,
  Trophy,
  Target,
  Clock,
  Users,
  Zap,
  BrainCircuit,
  Crown,
  Sparkles,
} from 'lucide-react';

// Danh sách thành tựu
export const achievements = [
  {
    id: 1,
    name: 'First Timer',
    description: 'Complete your first presentation',
    icon: Star,
    color: 'bg-blue-500',
    unlocked: true,
    progress: 100,
    date: '12/05/2023',
    points: 100,
    type: 'presentation',
  },
  {
    id: 2,
    name: 'Presentation Doctor',
    description: 'Create 10 presentations',
    icon: Award,
    color: 'bg-purple-500',
    unlocked: true,
    progress: 100,
    date: '28/06/2023',
    points: 250,
    type: 'presentation',
  },
  {
    id: 3,
    name: 'Content Star',
    description: 'Get 50 likes on your presentations',
    icon: Trophy,
    color: 'bg-yellow-500',
    unlocked: true,
    progress: 100,
    date: '03/08/2023',
    points: 300,
    type: 'presentation',
  },
  {
    id: 4,
    name: 'Design Talent',
    description: 'Use all premium templates',
    icon: Sparkles,
    color: 'bg-pink-500',
    unlocked: false,
    progress: 65,
    date: null,
    points: 400,
    type: 'presentation',
  },
  {
    id: 5,
    name: 'AI Hero',
    description: 'Create 20 slides using AI tools',
    icon: BrainCircuit,
    color: 'bg-cyan-500',
    unlocked: false,
    progress: 50,
    date: null,
    points: 350,
    type: 'presentation',
  },
  {
    id: 6,
    name: 'Quick Presenter',
    description: 'Complete a presentation in 30 minutes',
    icon: Clock,
    color: 'bg-green-500',
    unlocked: false,
    progress: 80,
    date: null,
    points: 200,
    type: 'presentation',
  },
  {
    id: 7,
    name: 'Collaboration Expert',
    description: 'Collaborate with 5 different users',
    icon: Users,
    color: 'bg-amber-500',
    unlocked: false,
    progress: 40,
    date: null,
    points: 300,
    type: 'presentation',
  },
  {
    id: 8,
    name: 'Presentation Master',
    description: 'Create 50 presentations',
    icon: Crown,
    color: 'bg-rose-500',
    unlocked: false,
    progress: 24,
    date: null,
    points: 500,
    type: 'presentation',
  },
  // Quiz achievements
  {
    id: 9,
    name: 'Quiz Beginner',
    description: 'Create your first quiz',
    icon: Target,
    color: 'bg-emerald-500',
    unlocked: true,
    progress: 100,
    date: '15/07/2023',
    points: 100,
    type: 'quiz',
  },
  {
    id: 10,
    name: 'Question Expert',
    description: 'Create 10 different quizzes',
    icon: BrainCircuit,
    color: 'bg-indigo-500',
    unlocked: false,
    progress: 40,
    date: null,
    points: 250,
    type: 'quiz',
  },
  {
    id: 11,
    name: 'Mind Challenger',
    description: 'Get 100 participants in your quizzes',
    icon: Users,
    color: 'bg-orange-500',
    unlocked: false,
    progress: 72,
    date: null,
    points: 300,
    type: 'quiz',
  },
  {
    id: 12,
    name: 'Comprehensive Test',
    description: 'Create a quiz with at least 5 different question types',
    icon: Sparkles,
    color: 'bg-sky-500',
    unlocked: true,
    progress: 100,
    date: '25/08/2023',
    points: 200,
    type: 'quiz',
  },
];

// Danh sách cấp độ thành tựu
export const levels = [
  { level: 1, name: 'Beginner', points: 0, color: 'bg-slate-500' },
  {
    level: 2,
    name: 'Amateur Presenter',
    points: 500,
    color: 'bg-blue-500',
  },
  {
    level: 3,
    name: 'Content Expert',
    points: 1000,
    color: 'bg-purple-500',
  },
  {
    level: 4,
    name: 'Presentation Master',
    points: 2000,
    color: 'bg-yellow-500',
  },
  {
    level: 5,
    name: 'Legendary Speaker',
    points: 5000,
    color: 'bg-rose-500',
  },
];

// Danh sách hoạt động gần đây
export const recentActivities = [
  {
    id: 1,
    action: 'Completed presentation',
    title: 'Marketing Plan 2023',
    date: 'Today',
    points: 100,
  },
  {
    id: 2,
    action: 'Unlocked achievement',
    title: 'Content Star',
    date: 'Yesterday',
    points: 300,
  },
  {
    id: 3,
    action: 'Used new template',
    title: 'Q2 Financial Report',
    date: '3 days ago',
    points: 50,
  },
  {
    id: 4,
    action: 'Collaborated with new user',
    title: 'John Smith',
    date: '1 week ago',
    points: 75,
  },
];

// CSS variables for colors
export const cssColorVariables = {
  '--blue-500-rgb': '59, 130, 246',
  '--purple-500-rgb': '168, 85, 247',
  '--green-500-rgb': '34, 197, 94',
  '--yellow-500-rgb': '234, 179, 8',
  '--emerald-500-rgb': '16, 185, 129',
  '--cyan-500-rgb': '6, 182, 212',
  '--amber-500-rgb': '245, 158, 11',
  '--rose-500-rgb': '244, 63, 94',
  '--indigo-500-rgb': '99, 102, 241',
  '--sky-500-rgb': '14, 165, 233',
  '--orange-500-rgb': '249, 115, 22',
  '--pink-500-rgb': '236, 72, 153',
};
